apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo-deployment
  namespace: release
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: eryzakaria14/user-service:${DOCKER_IMAGE}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: rollouts-demo-secrets
            - configMapRef:
                name: rollouts-demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-svc
  namespace: release
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: rollouts-demo-secrets
  namespace: release
type: Opaque
data:
  db-password: bXlwYXNzd29yZA==  # Password dalam base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollouts-demo-config
  namespace: release
data:
  DB_HOST: "localhost"
  DB_PORT: "3306"
