apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: eryzakaria14/user-service:$DOCKER_IMAGE
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: user-service-secrets
            - configMapRef:
                name: user-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: release
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      name: user-service
  selector:
    app: user-service
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: release
type: Opaque
data:
  db-password: bXlwYXNzd29yZA==  # Password dalam base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: release
data:
  DB_HOST: "localhost"
  DB_PORT: "3306"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
  namespace: release
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50