apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-vs2
  namespace: release
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "argorollout.devops.id"
  http:
  - name: route-one
    route:
    - destination:
        host: rollouts-demo-svc
        port:
          number: 80
        subset: stable
      weight: 100
    - destination:
        host: rollouts-demo-svc
        port:
          number: 80
        subset: canary
      weight: 0
